name: Tests & Build

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

jobs:
  test:
    name: run tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Run lint
        run: npm run lint

      - name: Run test
        run: npm run test -- --coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.0.5

  build:
    name: build packages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Run build
        run: npm run build
        env:
          BUILD_CONCURRENCY: 5
