name: Screenshots

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    name: run screenshots tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Install dependencies
        run: npm i

      - uses: microsoft/playwright-github-action@v1.5.1

      - name: Build storybook
        run: npm run build-storybook

      - name: Serve storybook
        run: npm run serve-storybook &

      - name: Run screenshots tests
        run: npm run test:screenshots

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Build output

      - name: Collect diff image artifacts
        id: diff_artifacts
        run: |
          images="${for file $(find . --type=file -path \*packages/**/__diff_output__/*.png); do "<li>$file</li>" done}"

      - name: Create comment
        if: failure()
        uses: peter-evans/create-or-update-comment@v2.0.0
        with:
          token: ${{ secrets.BOT_AUTH_TOKEN }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Failed screenshots tests 🙀
            <ul>(${{ steps.diff_artifacts.outputs.images }})</ul>
          reaction-type: 'eyes'

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: diffs
          path: packages/**/__diff_output__/*
          if-no-files-found: ignore
